#!/usr/bin/env bash
# Build and start a background rego server on port 2315. Use ./rc to send commands.

cd "$(dirname "${BASH_SOURCE[0]}")" || exit

if [[ -x "${JAVA_HOME:-}/bin/java" ]]; then
    readonly JAVA_CMD="$JAVA_HOME/bin/java"
else
    readonly JAVA_CMD=java
fi

./gradlew :repl:shadowJar || exit
"$JAVA_CMD" -jar repl/build/libs/repl-all.jar --serve &
disown
echo "Rego server starting on port 2315 (use ./rc to send commands)..."
