package dev.martianzoo.tfm.text

/** Why the current renderer left a Pets node unresolved. */
internal enum class RefusalReason {
  ACTION_ALTERNATIVES_NOT_COMBINABLE,
  REFINED_CHANGE_EXPRESSION,
  UNSUPPORTED_CARD_RESOURCE_CHANGE,
  UNSUPPORTED_DECLARED_CHANGE,
  UNSUPPORTED_DISCARD,
  UNSUPPORTED_DRAW,
  UNSUPPORTED_PLACEMENT_CHANGE,
  UNSUPPORTED_PRODUCTION_CHANGE,
  UNSUPPORTED_STANDARD_RESOURCE_CHANGE,
  UNSUPPORTED_TRACK_CHANGE,
  UNSUPPORTED_CHANGE_QUANTITY,
  UNKNOWN_ACTION_FRAME,
  UNKNOWN_CHANGE_FRAME,
  UNKNOWN_REQUIREMENT_FRAME,
  UNSUPPORTED_ACTION_CONDITION,
  UNSUPPORTED_ACTION_COST,
  UNSUPPORTED_ALTERNATIVES,
  UNSUPPORTED_END_EFFECT,
  UNSUPPORTED_FANOUT,
  UNSUPPORTED_EFFECT_TRIGGER,
  UNSUPPORTED_GATE,
  UNSUPPORTED_INSTRUCTION_KIND,
  UNSUPPORTED_SCALING,
  UNSUPPORTED_SEQUENCE,
}
