/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.martianzoo.tfm.data

import com.google.common.truth.Truth.assertThat
import kotlin.test.Test

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = Library()
        assertThat(classUnderTest.someLibraryMethod()).isTrue()
    }
}
